#!/usr/bin/expect
# Setzt das Verseichnis in dem das Skript liegt
set scriptdir "/skriptdir"

# Parameter auslesen
set host [lindex $argv 0]
set user [lindex $argv 1]
set pass [lindex $argv 2]

# Einstellungen
set timeout 1

# Automatischer Login
spawn ssh $user@$host $scriptdir/2.sh
expect "yes/no" {
  send "yes\r"
}
expect "password:" {
  send "$pass\r"
}

# Eingabe wieder an den Benutzer übergeben
interact
